version: 2

sources:
    - name: dev
      schema: dev
      tables:
        - name: raw_weather_data
          columns:
            - name: id
            - name: city
            - name: temperature
            - name: weather_desc
            - name: wind_speed
            - name: time
            - name: inserted_at
            - name: utc_offset
    
